title:  Jonnel Mendoza # your name (or website title) here
logo: "Github_pic.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring Data Analyst
  <br><br>
  I am an Art & Design graduate with a strong passion for Data Analytics. My experience in the Healthcare industry has enabled me to develop essential skills such as effective communication with diverse groups, both collaboratively and individually. I have also honed my problem-solving abilities and adopted a systematic approach to my work.

I am currently enrolled in a 12-week intensive Data Technician Bootcamp with Just IT Training, where I am enhancing my proficiency in tools such as Tableau, Power BI, SQL, Database Design – Access, Azure, and Python. Additionally, I am continually expanding my skills and knowledge in the field of Artificial Intelligence through ongoing learning on the IBM SkillsBuild platform.

My future aspirations include becoming a skilled Data Analyst who can leverage creative problem-solving and technical proficiency to drive insights and innovation in the Healthcare industry. Additionally, I aspire to continuously develop my skills and knowledge to stay at the forefront of the ever-evolving field of Data Analytics.
    

  <a href="https://www.linkedin.com/in/jonnelmendoza">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://public.tableau.com/app/profile/jonnel.mendoza/vizzes">View My Tableau Public</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
